#!/bin/sh
# URTEST is a CLI development task runner that invokes the URSYS CLI build library
# it lives inside of the _ur directory

source ./_set.sh

usage() {
    echo "Usage: ur {build|test}"
    exit 1
}

# Make sure NodeJS is installed
if ! command -v node > /dev/null 2>&1; then
    echo "Node.js not found. Please ensure it's installed."
    exit 1
fi

# If no arguments provided or unknown option, display usage
if [ $# -eq 0 ]; then
  usage
fi

case "$1" in
    build)
        # (1) always build library first
        node $OPTS $CLI_BUILD/@cli-build-lib.cjs 2>&1 | cat
        # (2) add additional tasks here (eventually can be command args)
        node $OPTS $MODS_BUILD/@ur-build-mods.cjs 2>&1 | cat
        ;;

    test)
        echo "would be running tests..."
        # npx ts-node-esm $TEST_BUILD/@test.mts 2>&1 | cat
        ;;

    *)
        usage
        ;;
esac






